"""add users, bots, relations, messages, intents

Revision ID: 6c4b101c9ed8
Revises: 
Create Date: 2023-03-01 20:47:30.090595

"""
from alembic import op
import sqlalchemy as sa
from fastapi_utils.guid_type import GUID, GUID_DEFAULT_SQLITE
from src.core.settings import settings
from src.services.utils.secure import hash_password


# revision identifiers, used by Alembic.
revision = '6c4b101c9ed8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    users = op.create_table('users',
        sa.Column('guid', GUID, nullable=False),
        sa.Column('login', sa.String(), nullable=False),
        sa.Column('password_hashed', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('guid'),
        sa.UniqueConstraint('login')
    )
    op.bulk_insert(users, [{
        'guid': GUID_DEFAULT_SQLITE(),
        'login': settings.admin_login,
        'password_hashed': hash_password(settings.admin_password),
    }])
    
    op.create_table('bots',
        sa.Column('guid', GUID, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('guid')
    )
    
    op.create_table('intents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('message', sa.Integer(), nullable=False),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.Column('created_by', GUID, nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('relations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_guid', GUID, nullable=False),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('intent_id', sa.Integer(), nullable=True),
        sa.Column('user_guid', GUID, nullable=False),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
        sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('relations')
    op.drop_table('intents')
    op.drop_table('users')
    op.drop_table('bots')
    # ### end Alembic commands ###
