"""v0.1.1

Revision ID: 94f4c24aca07
Revises: 
Create Date: 2023-03-04 23:17:56.733243

"""
from alembic import op
import sqlalchemy as sa
from fastapi_utils.guid_type import GUID, GUID_DEFAULT_SQLITE
from src.core.settings import settings
from src.services.secure import SecureService


# revision identifiers, used by Alembic.
revision = '94f4c24aca07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    users = op.create_table('users',
        sa.Column('guid', GUID, nullable=False),
        sa.Column('login', sa.String(), nullable=False),
        sa.Column('password_hashed', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('guid'),
        sa.UniqueConstraint('login')
    )
    op.bulk_insert(users, [{
        'guid': GUID_DEFAULT_SQLITE(),
        'login': settings.admin_login,
        'password_hashed': SecureService.hash_password(settings.admin_password),
    }])
    
    op.create_table('bots',
        sa.Column('guid', GUID, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('guid')
    )
    
    op.create_table('relations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_guid', GUID, nullable=False),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('admin_chat_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('user_guid', GUID, nullable=False),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.Column('intent_rank', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('client_chat_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('in_doubt', sa.Boolean(), nullable=True),
        sa.Column('client_id', sa.String(), nullable=False),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.Column('intent_rank', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('intents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('answer', sa.String(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('bot_guid', GUID, nullable=False),
        sa.Column('created_by', GUID, nullable=False),
        sa.ForeignKeyConstraint(['bot_guid'], ['bots.guid'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('relations')
    op.drop_table('intents')
    op.drop_table('client_chat_log')
    op.drop_table('admin_chat_log')
    op.drop_table('users')
    op.drop_table('bots')
    
    # ### end Alembic commands ###
